package org.client.lead;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-05-14T22:41:34.814+02:00
 * Generated source version: 2.7.13
 * 
 */
@WebServiceClient(name = "PartnerzyService", 
                  wsdlLocation = "file:/home/mariusz/szkola/systemy_rozproszone/projekty/leads/src/main/resources/META-INF/PartnerzyService.wsdl",
                  targetNamespace = "http://localhost/test/wsdl") 
public class PartnerzyService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://localhost/test/wsdl", "PartnerzyService");
    public final static QName PartnerzyPort = new QName("http://localhost/test/wsdl", "PartnerzyPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/mariusz/szkola/systemy_rozproszone/projekty/leads/src/main/resources/META-INF/PartnerzyService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PartnerzyService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/mariusz/szkola/systemy_rozproszone/projekty/leads/src/main/resources/META-INF/PartnerzyService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PartnerzyService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PartnerzyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PartnerzyService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PartnerzyService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PartnerzyService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PartnerzyService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns LeadService
     */
    @WebEndpoint(name = "PartnerzyPort")
    public LeadService getPartnerzyPort() {
        return super.getPort(PartnerzyPort, LeadService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LeadService
     */
    @WebEndpoint(name = "PartnerzyPort")
    public LeadService getPartnerzyPort(WebServiceFeature... features) {
        return super.getPort(PartnerzyPort, LeadService.class, features);
    }

}
